spring:
  config:
    activate:
      on-profile: prod
  main:
    lazy-initialization: true
  mvc:
    servlet:
      load-on-startup: 1
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    jpa:
      repositories:
        bootstrap-mode: lazy
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.boot.allow_jdbc_metadata_access: false

server:
  shutdown: graceful
  servlet:
    session:
      cookie:
        http-only: true
        same-site: lax
        secure: true

